"""Default vocabulary for transcription accuracy improvement.

This module contains domain-specific technical terms that improve
Whisper's recognition accuracy for AI-driven development content.
"""

DEFAULT_VOCABULARY: tuple[str, ...] = (
    # AI サービス・プラットフォーム
    "Claude",
    "Claude Code",
    "Claude Sonnet 4",
    "Claude Sonnet 4.5",
    "Claude Opus 4",
    "Claude Opus 4.5",
    "Claude Haiku",
    "Claude Pro",
    "Claude Max",
    "Anthropic",
    "ChatGPT",
    "GPT-4",
    "GPT-4o",
    "GPT-5",
    "GPT-5-Codex",
    "OpenAI",
    "Gemini",
    "Gemini CLI",
    "Perplexity",
    "DeepSeek",
    "Whisper",
    "SuperClaude",
    # AI コーディングツール・エージェント
    "Cursor",
    "Windsurf",
    "Cline",
    "Codex",
    "Codex CLI",
    "GitHub Copilot",
    "Bolt.new",
    "Lovable.dev",
    "v0",
    "Replit",
    "Kiro",
    "AWS Kiro",
    # MCP (Model Context Protocol) 関連
    "MCP",
    "Model Context Protocol",
    "Playwright MCP",
    "filesystem MCP",
    "Slack MCP",
    "Desktop Commander",
    "Serena",
    "Context7",
    "Supabase MCP",
    "Brave Search MCP",
    "Obsidian MCP",
    "Chrome DevTools MCP",
    "GitHub MCP",
    "PostgreSQL MCP",
    "Notion MCP",
    "Sentry MCP",
    # AI 開発フレームワーク・SDK
    "LangChain",
    "LlamaIndex",
    "Semantic Kernel",
    "OpenAI Agents SDK",
    "Claude Agent SDK",
    "LiteLLM",
    "Ollama",
    # Claude Code 機能・コンポーネント
    "CLAUDE.md",
    ".claude",
    ".claude/rules",
    ".clauderules",
    ".claude/commands",
    ".claude/agents",
    ".claude/settings.json",
    ".claude/mcp.json",
    ".mcp.json",
    "サブエージェント",
    "Sub agents",
    "カスタムコマンド",
    "スラッシュコマンド",
    "Skills",
    "スキル",
    "Plugins",
    "プラグイン",
    "hooks",
    "フック",
    "frontmatter",
    "フロントマター",
    "Glob",
    "Grep",
    "opusplan",
    "Plan mode",
    "プランモード",
    "コンテキストウィンドウ",
    "context window",
    "トークン",
    "プロンプトキャッシュ",
    # データベース・バックエンドサービス
    "Supabase",
    "Firebase",
    "PostgreSQL",
    "Neon",
    "Vercel",
    "Netlify",
    "Render.com",
    "Railway",
    "PlanetScale",
    "Cloudflare",
    "AWS",
    "GCP",
    "Azure",
    # 認証・決済サービス
    "Clerk",
    "Auth0",
    "Stripe",
    "RevenueCat",
    "Superwall",
    # テスト・品質管理ツール
    "Playwright",
    "Sentry",
    "Jest",
    "Vitest",
    "RSpec",
    "pytest",
    "E2E",
    # 自動化ツール
    "n8n",
    "Zapier",
    "Make",
    # 開発手法・概念
    "Vibe Coding",
    "バイブコーディング",
    "AI駆動開発",
    "仕様駆動開発",
    "Spec Driven Development",
    "SDD",
    "TDD",
    "cc-sdd",
    "Spec Driven Codex",
    "Build in Public",
    "Issue駆動開発",
    "エージェント型",
    "ハルシネーション",
    "Prompt Engineering",
    "プロンプトエンジニアリング",
    "コンテキストエンジニアリング",
    "RAG",
    "Fine-tuning",
    "ファインチューニング",
    "Few-shot Learning",
    "Chain-of-Thought",
    "SWE-bench",
    "OWASP",
    "DRY原則",
    "PARA Method",
    "Onion Architecture",
    "DDD",
    # プログラミング言語・フレームワーク
    "TypeScript",
    "JavaScript",
    "Python",
    "Ruby",
    "Rails",
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Node.js",
    "Express",
    "FastAPI",
    "Django",
    "Flask",
    "Swift",
    "SwiftUI",
    "Kotlin",
    "Flutter",
    "Go",
    "Rust",
    "Tailwind CSS",
    "shadcn/ui",
    "Radix UI",
    "Chakra UI",
    "Framer Motion",
    # 開発ツール・パッケージマネージャー
    "VS Code",
    "Visual Studio Code",
    "Git",
    "GitHub",
    "GitHub CLI",
    "npm",
    "yarn",
    "pnpm",
    "Bun",
    "uv",
    "pip",
    "poetry",
    "Docker",
    "Kubernetes",
    "Terraform",
    "ESLint",
    "Prettier",
    "Biome",
    "Vite",
    "Webpack",
    "Git worktree",
    # API・プロトコル
    "REST",
    "RESTful",
    "GraphQL",
    "WebSocket",
    "SSE",
    "gRPC",
    "tRPC",
    "API",
    "Endpoint",
    "JSON",
    "YAML",
    "Markdown",
    # 学習・教育プラットフォーム
    "Udemy",
    "Learning Next",
    "Qiita",
    "Zenn",
    "note",
    "Zenn Book",
    # SNS・コミュニケーション
    "X",
    "Twitter",
    "YouTube",
    "Instagram",
    "Voicy",
    "Discord",
    "Slack",
    "Notion",
    "Obsidian",
    # とまだ独自
    "Vibe Coding Studio",
    "とまだ",
    # iOS / Apple 開発関連
    "Apple Developer Program",
    "App Store",
    "TestFlight",
    "Xcode",
    "iOS",
    "macOS",
    "Core Data",
    "CloudKit",
    "HealthKit",
    "StoreKit",
    # セキュリティ関連
    "XSS",
    "CSRF",
    "SQL Injection",
    "OAuth",
    "OAuth 2.0",
    "JWT",
    "API Key",
    ".env",
    # パフォーマンス関連
    "ボトルネック",
    "レイテンシ",
    "キャッシュ",
    "CDN",
    "SSR",
    "CSR",
    "ISR",
    "SSG",
    # その他技術用語
    "CI/CD",
    "デプロイ",
    "マイグレーション",
    "リファクタリング",
    "技術的負債",
    "コードレビュー",
    "プルリクエスト",
    "PR",
    "Issue",
    "Conventional Commits",
    "モノレポ",
    "マイクロサービス",
    "コンポーネント",
    "ミドルウェア",
    "ORM",
    "Prisma",
    "Drizzle",
    "N+1問題",
    # ビジネス・収益関連
    "フリーランス",
    "個人開発",
    "副業",
    "収益化",
    "SEO",
    "MRR",
    "LTV",
    # 画像・動画生成AI
    "Stable Diffusion",
    "DALL-E",
    "Midjourney",
    "Seedream",
    "Seedream 4.0",
    "生成AI",
    "Filmora",
    "FILMORA",
    # LLM関連
    "LLM",
    "Large Language Model",
    "大規模言語モデル",
    "Transformer",
    "Embedding",
    "Vector Database",
    "Pinecone",
    "Weaviate",
    "Chroma",
)
